on:
  push:
    branches:
      - master
jobs:
  updateGraphs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysoc_dataset
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update Tables
        run: python main.py --refresh

      - name: Update graphs
        run: |
          git config --global user.name 'Mike Johnson'
          git config --global user.email 'm-d-johnson@users.noreply.github.com'
          git commit -am "Update tables"
          git push